# Generated by Django 4.0.3 on 2023-01-27 02:55

from django.conf import settings
from django.db import migrations, models
from main.models import CategoriaProd, User, Anuncio
import django.db.models.deletion

def populate_categorias(apps, schema_editor):
    CategoriaProd = apps.get_model('main', 'CategoriaProd')
    lista = ['Veículos', 'Supermercado', 'Tecnologia', 'Casa e móveis', 'Eletrodomésticos', 
    'Esportes e Fitness', 'Ferramentas', 'Construção', 'Indústria e Comércio', 'Saúde', 
    'Acessórios para veículos', 'Beleza e Cuidado Pessoal', 'Moda', 'Bebês', 'Brinquedos', 
    'Imóveis']
    for x in lista:
        obj = CategoriaProd(categoriaprod=x)
        obj.save()

def populate_anuncios(apps, shcema_editor):
    Anuncio = apps.get_model('main', 'Anuncio')
    CategoriaProd = apps.get_model('main', 'CategoriaProd')
    User = apps.get_model('main', 'User')
    obj1 = Anuncio(nome='Celular', categoriaprod=CategoriaProd.objects.get(categoriaprod='Tecnologia'), 
    descricao='Celular usado, em bom estado.', preco=500, vendedor=User.objects.get(username='demonstracao'),
    )
    obj2 = Anuncio(nome='Notebook', categoriaprod=CategoriaProd.objects.get(categoriaprod='Tecnologia'), 
    descricao='Notebook usado, em bom estado.', preco=500, vendedor=User.objects.get(username='demonstracao'),
    )
    obj3 = Anuncio(nome='Fogão', categoriaprod=CategoriaProd.objects.get(categoriaprod='Eletrodomésticos'), 
    descricao='Fogão usado, em bom estado.', preco=200, vendedor=User.objects.get(username='demonstracao'),
    )
    obj4 = Anuncio(nome='Geladeira', categoriaprod=CategoriaProd.objects.get(categoriaprod='Eletrodomésticos'), 
    descricao='Geladeira usada, em bom estado.', preco=300, vendedor=User.objects.get(username='demonstracao'),
    )
    obj1.save()
    obj2.save()
    obj3.save()
    obj4.save()

def populate_imagens(apps, schema_editor):
    Anuncio = apps.get_model('main', 'Anuncio')
    Imagens = apps.get_model('main', 'Imagens')
    img1 = Imagens(imagem='https://res.cloudinary.com/ddtbyedw7/image/upload/v1674789136/imagens/celular1_yyoycx.jpg', 
    anuncio=Anuncio.objects.get(nome='Celular'))
    img2 = Imagens(imagem='https://res.cloudinary.com/ddtbyedw7/image/upload/v1674789136/imagens/celular2_korcyk.jpg', 
    anuncio=Anuncio.objects.get(nome='Celular'))
    img3 = Imagens(imagem='https://res.cloudinary.com/ddtbyedw7/image/upload/v1674789136/imagens/notebook1_s72k3b.jpg', 
    anuncio=Anuncio.objects.get(nome='Notebook'))
    img4 = Imagens(imagem='https://res.cloudinary.com/ddtbyedw7/image/upload/v1674789136/imagens/notebook2_owqylv.jpg', 
    anuncio=Anuncio.objects.get(nome='Notebook'))
    img5 = Imagens(imagem='https://res.cloudinary.com/ddtbyedw7/image/upload/v1674789136/imagens/fogao1_xxsmlu.jpg', 
    anuncio=Anuncio.objects.get(nome='Fogão'))
    img6 = Imagens(imagem='https://res.cloudinary.com/ddtbyedw7/image/upload/v1674789136/imagens/fogao2_pffvfe.webp', 
    anuncio=Anuncio.objects.get(nome='Fogão'))
    img7 = Imagens(imagem='https://res.cloudinary.com/ddtbyedw7/image/upload/v1674789136/imagens/geladeira2_a4xblj.webp', 
    anuncio=Anuncio.objects.get(nome='Geladeira'))
    img8 = Imagens(imagem='https://res.cloudinary.com/ddtbyedw7/image/upload/v1674789136/imagens/geladeira1_jzsdo1.webp', 
    anuncio=Anuncio.objects.get(nome='Geladeira'))
    img1.save()
    img2.save()
    img3.save()
    img4.save()
    img5.save()
    img6.save()
    img7.save()
    img8.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('preco', models.FloatField()),
                ('anunciado', models.DateTimeField(auto_now_add=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('comprado', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-anunciado'],
                'get_latest_by': 'anunciado',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriaprod', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anuncio')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='categoriaprod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_anuncio', to='main.categoriaprod'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='carrinho',
            field=models.ManyToManyField(to='main.anuncio'),
        ),
        migrations.AddField(
            model_name='user',
            name='compras',
            field=models.ManyToManyField(related_name='itens_comprados', to='main.anuncio'),
        ),
        migrations.RunPython(populate_categorias),
        migrations.RunPython(populate_anuncios),
        migrations.RunPython(populate_imagens)
    ]
